testing-library/eslint-plugin-testing-library

- lib/rules/await-async-query.js
- tests/lib/rules/await-async-query.js
This PR intends to support the edge cases of the queries usage. That is to say:
- Assignments of the queries : 
```js
const promise = findByText('foo')
return promise
```
- Promise syntax
```js
const promise = findByText('foo')
promise.then(node => done())
// Or
findByText('foo').then(node => {
done()
})
```
All tests passes but I consider the implementation to be a bit fragile.
Closes #1 
Closes #2
> feat: support assignments and promise syntax

- README.md
- docs/rules/no-debug.md
- lib/rules/no-debug.js
- tests/lib/rules/no-debug.js
This PR intends to add a new rule called `no-debug`.
Indeed, just like `console.log` statements pollutes the browser's output, debug statements can also pollute the tests:
```js
import React from 'react'
import { render } from '@testing-library/react'
const HelloWorld = () => <h1>Hello World</h1>
const { debug } = render(<HelloWorld />)
debug()
// <div>
//   <h1>Hello World</h1>
// </div>
```
This rule would prevent developers to push unwanted debug statements to the codebase by warning them that it has been used.
> feat: add no-debug

- .eslintrc.json
- .huskyrc
- README.md
- commitlint.config.js
- lib/index.js
- lib/rules/await-async-query.js
- package-lock.json
- package.json
- tests/__snapshots__/index.js.snap
- tests/index.js
This PR adds shareable framework configs (angular, react, vue) and updates corresponding documentation.
Apart from the setup itself, I've enabled `no-debug` rule for all these 3 frameworks included.
Additionally, I've added some snapshots tests for exposed configs so we have a way to test if they are changed or not flexible enough to be updated easily when adding/modifying rules. Related to this, I added couple of eslint plugins for jest as this is the first test file purely written in jest syntax.
> feat: add shareable framework configs

- .huskyrc
- lib/rules/await-async-query.js
- tests/lib/rules/await-async-query.js
We had a failing test case where an immediately awaited call assigned to a var would be tracked by our rule. This PR intends to fix this behavior for `await` and `.then`.
I also made sure the tests would be run on each commit to add a layer of safety in case someone commits code that would make tests fail. Tell me if you're OK with this 🙂
> fix: immediately awaited assign to var

- lib/index.js
- tests/__snapshots__/index.test.js.snap
- tests/index.test.js
With this improvement the test will check that all the rules available under 'lib/rules' folder are properly exposed in the plugin so we avoid to forget adding new rules after create them.
> Feature: improve exported rules test

- docs/rules/no-dom-import.md
- lib/index.js
- lib/rules/no-dom-import.js
- tests/__snapshots__/index.test.js.snap
- tests/lib/rules/no-dom-import.js
Just one thing to check before merging. The corresponding error message for a framework is the following: 
```
import from DOM Testing Library is restricted, import from @testing-library/{{name}} instead
```
Should we keep the same error message if the user is using the old libraries (`react-testing-library` for example)? I assume yes as the old ones are deprecated, but still I wanted to check that with you.
> feat: suggest proper framework to import from

- lib/rules/await-async-query.js
- tests/lib/rules/await-async-query.js
Avoid duplicated errors for `await-async-query` for each use of the var declarated.
> fix(await-async-query): avoid duplicated reports

- README.md
- docs/rules/await-fire-event.md
- lib/index.js
- lib/rules/await-fire-event.js
- tests/__snapshots__/index.test.js.snap
- tests/lib/rules/await-fire-event.js
Adds new rule `await-fire-event` for waiting special async `fireEvent` methods (only for Vue).
> feat: add new rule await-fire-event

- docs/rules/no-debug.md
- lib/rules/no-debug.js
- tests/lib/rules/no-debug.js
we commonly wrap `render` with redux and other things, so having the ability to configure the render function names will be useful for us.
> feat(no-debug): render function names

- README.md
- docs/rules/prefer-expect-query-by.md
- lib/index.js
- lib/rules/prefer-expect-query-by.js
- package-lock.json
- tests/__snapshots__/index.test.js.snap
- tests/lib/rules/prefer-expect-query-by.js
Closes #21 
This a port of the implementation of the rule `prefer-expect-query-by` from [this package](https://www.npmjs.com/package/eslint-plugin-testing-library-react).
As mentioned, we would like to eventually deprecate our own package in favor of this one, as it has more rules.
Let me know if the rule is "good enough" for now. We've already been using it in our apps and works great so far.
> feat(rule): prefer expect queryBy

- jest.config.js
- package-lock.json
- package.json
> chore: enforce 100% coverage on CI

- .travis.yml
Limit CI branches to master to avoid unnecessary builds in Travis. In previous PRs, builds were executed twice: one from PR and one from new push. This PR aims to fix that so we only have one build in that case.
Previous checks:
Current checks:
> ci: limit branches to master

- lib/rules/prefer-explicit-assert.js
- lib/utils.js
- tests/lib/rules/prefer-explicit-assert.js
Closes #40.
I've added a check for Array destructuring. I've never seen it before, but I thought it wouldn't hurt.
Thanks for your help!
> Fix prefer-explicit-assert raising error on destructuring statement

- docs/rules/prefer-explicit-assert.md
Fix a broken link in the docs from `prefer-explicit-assert.md` to `prefer-expect-query-by.md`.
URL Before (note "docs/rules/docs/rules"):
https://github.com/Belco90/eslint-plugin-testing-library/blob/master/docs/rules/docs/rules/prefer-expect-query-by.md
URL After:
https://github.com/Belco90/eslint-plugin-testing-library/blob/master/docs/rules/prefer-expect-query-by.md
> docs: fix broken link to prefer-expect-query-by

- lib/rules/await-async-query.js
- tests/lib/rules/await-async-query.js
The bug was caused by the fact that when a query is wrapped into a function, it is not referenced in the `getDeclaredVariables` call making the references equal to `false`.
It caused the references check to be false, to enter the else statement and thus trying to iterate over a false value.
Closes #48.
> fix: references is not iterable / cant parse expect(findBy*)

- lib/rules/prefer-explicit-assert.js
- tests/lib/rules/prefer-explicit-assert.js
In cases like `expect(getBy("foo").bar)`, `bar` was considered as an identifier thus triggering the visited function (`CallExpression Identifier`) and reporting an error.
Instead of adding another check, the implementation is simpler: checking whether the node is at the top level or not (`ExpressionStatement`).
Closes #45
> fix: prefer explicit assert should check if node property is accessed

- docs/rules/prefer-expect-query-by.md
- lib/index.js
- tests/__snapshots__/index.test.js.snap
As mentioned in the original issue #59 :
- remove `prefer-expect-query-by` rule from shareable configs
- improve doc
> Remove `prefer-expect-query-by` rule from shareable configs

- docs/rules/await-async-query.md
- lib/rules/await-async-query.js
- tests/lib/rules/await-async-query.js
> feat: add support for resolves/rejects matchers in async queries

- README.md
- lib/rules/prefer-expect-query-by.js
- lib/utils.js
- package.json
As this project was previously at my repo, it would be better to replace some references to it. I'm not replacing references in contributors section of README as comments from the bot says "Do not remove or modify this section".
> chore: replace previous repo references

- README.md
Contributors badge count is not properly updated. Applying [this change mentioned in their docs](https://allcontributors.org/docs/en/bot/faq#all-contributors-badge-count-does-not-update) should fix it.
> docs: fix contributors badge count

- README.md
- docs/rules/await-async-utils.md
- lib/index.js
- lib/rules/await-async-utils.js
- lib/utils.js
- tests/__snapshots__/index.test.js.snap
- tests/lib/rules/await-async-utils.js
> feat: new rule await-async-utils

- docs/rules/no-debug.md
- lib/rules/no-debug.js
- tests/lib/rules/no-debug.js
`screen` export was added in [`@testing-library/dom@6.12.0`](https://github.com/testing-library/dom-testing-library/releases/tag/v6.12.0).
I think `no-debug` rule should also take into consideration the `screen.debug()` as it's basically just an utility to console.log entire testing container.
ref: https://github.com/testing-library/dom-testing-library/pull/429
> feat(no-debug): scan for `screen.debug()`

- docs/rules/prefer-explicit-assert.md
As spotted in #74 we still have references to non-existing prefer-expect-query-by rule within prefer-explicit-assert doc. This PR removes all those references as they don't make sense anymore.
> docs(prefer-explicit-assert): remove references to old rule

- lib/rules/no-debug.js
- tests/lib/rules/no-debug.js
> fix: support async render

- lib/rules/no-debug.js
- tests/lib/rules/no-debug.js
The code used in the tests currently results in an exception as callee does not exist.
This ensures it's there.
> fix(no-debug): ensure callee exists

- docs/rules/no-get-by-for-checking-element-not-present.md
- lib/rules/no-get-by-for-checking-element-not-present.js
- package.json
- tests/lib/rules/no-get-by-for-checking-element-not-present.js
> fix(no-get-by-for-checking-element-not-present): false positives for negated matchers

- docs/rules/await-async-utils.md
- lib/utils.js
- tests/lib/rules/await-async-utils.js
> feat(await-async-utils): reflect waitFor changes

- README.md
- docs/rules/no-wait-for-empty-callback.md
- lib/index.js
- lib/rules/no-wait-for-empty-callback.js
- tests/lib/rules/no-wait-for-empty-callback.js
Closes #92 
This rule covers:
- empty arrow function (i.e. `() => {}`)
- empty regular function (i.e. `function () {}`)
- a function or var called `noop`
Inspired by eslint no-empty-function rule
> feat(no-wait-for-empty-callback ): new rule no-wait-for-empty-callback 

- .travis.yml
BREAKING CHANGE: Drop support for node v8. Min version allowed is node
v10.12
> ci(await-async-query): update node versions

- lib/rules/no-debug.js
- lib/rules/prefer-wait-for.js
- tests/lib/rules/no-debug.js
- tests/lib/rules/prefer-wait-for.js
> fix: check namespaced import properly for `no-debug` and `prefer-wait-for`

- lib/rules/no-debug.js
> fix(no-debug): enable for angular

- docs/rules/prefer-presence-queries.md
Fix some wrong examples around `toBeNull` matcher on `prefer-presence-queries` doc.
> docs(prefer-presence-queries): fix examples

- lib/rules/consistent-data-testid.js
- lib/rules/no-manual-cleanup.js
- tests/index.test.js
Add missing references to docs.
Also point missing export tests to the rules of the lib, instead of the tests.
> fix: add missing doc urls

- CONTRIBUTING.md
- package.json
Add contributing guidelines, including
- Project setup
- Committing and Pushing changes
- Rule naming conventions
- Adding new rules
- Modifying rules
> docs: add contributing guidelines

- docs/rules/prefer-screen-queries.md
- lib/rules/prefer-screen-queries.ts
- tests/lib/rules/prefer-screen-queries.test.ts
I am pretty new to writing/fixing ESlint rules, so I might be doing something wrong 😄 
This should fix #116  so this code
```jsx
import { render, within, screen } from 'react-testing-library';
// ...
render(<SomeComponent />);
const section = screen.getByTestId('some-id');
// this is fine but the rule complains about it.
const submit = within(section).getByText(/submit/i);
```
should now be valid
I think this scenario is still pending
```
const { getByText } = within(foo)
getByText(/submit/)
```
perhaps I could do another PR for that one. I am still new to AST so there's probably a better way to do this one.
Thank you very much!
> fix(prefer-screen-queries): false positives when using within method

- lib/rules/await-async-utils.ts
- lib/rules/no-debug.ts
- lib/utils.ts
- tests/lib/rules/await-async-utils.test.ts
Closes #118; Related #122
Fixes false positives `no-await-sync-query`
> fix(await-async-utils): false positives

- docs/rules/consistent-data-testid.md
I just noticed the docs don't have the correct rule name here as I was having some trouble getting it to work.
> fix: correct consistent-data-testid docs example

- README.md
- docs/rules/prefer-find-by.md
- lib/index.ts
- lib/node-utils.ts
- lib/rules/prefer-find-by.ts
- tests/__snapshots__/index.test.ts.snap
- tests/lib/rules/prefer-find-by.test.ts
This one tackle #127 
While current code works, I still have to polish some stuff and add more scenarios (and update the docs)
> feat: add prefer-find-by rule

- docs/rules/prefer-screen-queries.md
- lib/rules/prefer-screen-queries.ts
- tests/lib/rules/prefer-screen-queries.test.ts
> fix(prefer-screen-queries): take container into account

- lib/rules/prefer-wait-for.ts
- tests/lib/rules/prefer-wait-for.test.ts
> fix(prefer-wait-for): only report when imported from TL

- docs/rules/prefer-screen-queries.md
- lib/rules/prefer-screen-queries.ts
- tests/lib/rules/prefer-screen-queries.test.ts
Reverts testing-library/eslint-plugin-testing-library#150
Fixes #156 
`container` is not exposed through `screen` - so the only way to access container is by using it in the `render result.`
Therefore, what we thought it was a bug in #149 is actually a valid scenario
> fix(prefer-screen-queries): revert "take container into account"

- docs/rules/prefer-screen-queries.md
- tests/lib/rules/prefer-screen-queries.test.ts
Requires rebasing after #157  is merged. The changes are in this commit f17275e
edit: The properties + methods I included come from the typings here https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/testing-library__react/index.d.ts#L19
> docs(prefer-screen-queries): update allowed properties and methods

- lib/node-utils.ts
- tests/lib/rules/prefer-find-by.test.ts
This fixes an issue where the linter blows up when there are no arguments in `wait()` or `waitFor()`
> fix: ensure node exists before using in isArrowFunctionExpression

- .travis.yml
- package.json
Update CI matrix to run tests combining supported node versions (v10.12, v12, v14) and ESLint versions (v5, v6). This will help adding support for ESLint v7 in #139
I'm not sure how to test or dry run the release stage, so I may need to readjust something when this PR is merged (unless someone can help me testing this locally).
> ci: include eslint matrix

- lib/rules/no-debug.ts
- tests/lib/rules/no-debug.test.ts
> fix(no-debug): catch all screen imports

- tests/lib/rules/prefer-wait-for.test.ts
Seems like we fixed this already, just added a test to verify it.
Closes #145
> test: add test for #145

- lib/rules/prefer-find-by.ts
- tests/lib/rules/prefer-find-by.test.ts
This PR fixes #167 
The following scenario
```ts
// incorrect
const { getByText } = render(<Foo />)
await waitFor(() => getByText('foo'))
```
now becomes
```ts
// correct - and findByText is defined
const { getByText, findByText } = render(<Foo />)
await findByText('foo')
```
this should even work if they are in different levels. For instance
```ts
// incorrect
const { getByText } = render(<Foo />)
it('tests', async () => {
await waitFor(() => getByText('foo'))
})
```
should be converted to
```ts
// correct - findByText is defined
// as long as the customRender is in any parent scope from the original code, this works
const { getByText, findByText } = customRender(<Foo />)
it('tests', async () => {
await findByText('foo')
})
```
there are some scenarios that I assume they are out of …
> fix: add findby variable declaration to prefer-find-by when auto fixing

- docs/rules/prefer-screen-queries.md
- lib/node-utils.ts
- lib/rules/prefer-screen-queries.ts
- tests/lib/rules/prefer-screen-queries.test.ts
closes #188 
One thing I noticed from this rule is that it does not check `screen` is imported from RTL, nor anything about custom renders. Not sure if we should all of that for the v4 in #198 or if checking imports should be done in a separated ticket for the current version and then enhanced with custom renders for the v4... I'll assume it will be easier to do everything directly in v4 to avoid doing weird rebases but I want to know your opinion folks.
For this PR I just stick with the feature requested
> feat: allow baseElement and container in prefer-screen-queries

- CONTRIBUTING.md
We forgot to update the `CONTRIBUTING.md` file after the TypeScript migration.
This PR reflects some changes (`.js` -> `.ts`)
> docs: update contributing.md after typescript migration

- README.md
- docs/rules/prefer-wait-for.md
- lib/node-utils.ts
- lib/rules/prefer-find-by.ts
This will migrate all of the hardcoded type guards to use the ENUM provided by `@typescript-eslint/experimental-utils`. There is also a couple of minor diffs to formatting after running `npm run format` and to fix some linting errors.
> refactor node-utils type guards to use the AST_NODE_TYPES enum

- lib/node-utils.ts
- lib/rules/await-async-query.ts
- lib/rules/await-async-utils.ts
- lib/rules/await-fire-event.ts
- tests/lib/rules/await-async-query.test.ts
Closes #122.
- Move `isAwaited` and `isPromiseResolved` to `node-utils.ts` that was used in three different rules (`await-async-utils`, `await-async-query`, `await-fire-event`)
- Prevent the `await-async-query` rule to fire if nothing is imported from one of the testing library modules as declared in `LIBRARY_MODULES` in `utils.ts`.
- Refactor the test cases in `await-async-query` to get closer to a real test case
Note that this is a partial improvement to the rule. Indeed, if one is using (and importing) a custom render function in his tests, he won't benefit from the rule as this function would not be imported from a testing library module such as `@testing-library/react` or `@testing-library/vue`.
A fix to that would be to allow the user to input what custom render function he uses, …
> fix(await-async-query): false positives for await-async-query

- README.md
- docs/rules/no-render-in-setup.md
- lib/index.ts
- lib/node-utils.ts
- lib/rules/no-debug.ts
- lib/rules/no-manual-cleanup.ts
- lib/rules/no-render-in-setup.ts
- lib/utils.ts
- tests/lib/rules/no-render-in-setup.test.ts
Added a `no-render-in-setup` rule with tests to address https://github.com/testing-library/eslint-plugin-testing-library/issues/207.
The rule looks for uses of `render` (or a custom render function who name can be passed in via config options) inside of two "before hooks": `beforeEach` and `beforeAll`.
> feat(no-render-in-setup): adds no-render-in-setup rule, closes #207

- docs/rules/consistent-data-testid.md
- lib/rules/consistent-data-testid.ts
- tests/lib/rules/consistent-data-testid.test.ts
This PR proposes adding support for multiple test id attributes (via `testIdAttribute`) to the `consistent-data-testid` rule. 
When making shared components, some prefer to expose a `testId` prop ([example in Atlastkit](https://atlaskit.atlassian.com/packages/design-system/button)) in addition to using the `data-testid` prop. Ideally, this linting rule could handle more than one test id attribute to handle cases like this.
The configuration was updated to allow either a `string` (existing API) or now an array of strings.  This was done so the rule continues to work with existing configurations. I also considered adding regex support which could also achieve this and happy to update with that approach if preferred.
> feat: add support for multiple test id attributes

- README.md
- docs/rules/no-wait-for-snapshot.test.md
- lib/index.ts
- lib/node-utils.ts
- lib/rules/no-wait-for-snapshot.ts
- tests/lib/rules/no-wait-for-snapshot.test.ts
✅ Closes: #214
The rule is checking for all async utils not only `wait`. If that's not the preferred behavior I can change it back. It's my first contribution to this project so any feedback is welcome 😄
> feat: 🎸 new no-wait-for-snapshot rule

- .travis.yml
- lib/rules/consistent-data-testid.ts
- lib/rules/no-debug.ts
- lib/rules/no-render-in-setup.ts
- lib/rules/prefer-find-by.ts
- package-lock.json
- package.json
ESLint v7.0.0 is [released](https://eslint.org/blog/2020/05/eslint-v7.0.0-released) 🎉
(dev)Dependencies should be compatible with ESLint 7 too before we can merge this one:
---
Closes #138
> feat: Support ESLint 7.x

- docs/rules/await-async-utils.md
- jest.config.js
- lib/node-utils.ts
- lib/rules/await-async-utils.ts
- tests/lib/rules/await-async-utils.test.ts
closes #227 
After a while, trying to program a Lil' bit outside of my regular work again. Here I'm just fixing the referenced ticket. I also added a bunch of helpers to `node-utils` instead of checking the node's type directly in the rule
> fix: consider promise.all() in await-async-utils

- docs/rules/prefer-explicit-assert.md
- lib/rules/prefer-explicit-assert.ts
- lib/rules/prefer-presence-queries.ts
- lib/utils.ts
- tests/lib/rules/prefer-explicit-assert.test.ts
This is a follow-up improvement to issue https://github.com/testing-library/eslint-plugin-testing-library/issues/218.
The original implementation was flawed.  With the way this was implemented, any `getBy*` query will trigger a linting error if it's not using `toBeInTheDocument` (assuming the config defined the `assertion` to use as `toBeInTheDocument`). However, there are still valid cases to use a different assertion. For example, if you want to check if a button is disabled (`toBeDisabled`) or maybe check if an anchor has the appropriate `href` attribute (`toHaveAttribute`).
With the way the rule was implemented, both of these examples would trigger as violations (since they're not using `toBeInTheDocument`) but they're both still valid uses of `getBy*` and thus are false positives. …
> fix(prefer-explicit-assert): only enforce assertion when presence/absence matcher

- jest.config.js
- lib/create-testing-library-rule.ts
- lib/detect-testing-library-utils.ts
- lib/rules/no-node-access.ts
- tests/create-testing-library-rule.test.ts
- tests/fake-rule.ts
- tests/lib/rules/no-node-access.test.ts
Second part which includes:
- shared config to be able to set module where Testing Library utils can be imported from
- mechanism to check if Testing Library is considered as imported depending on shared config
- aggressive reporting by default
So the plugin is gonna assume that Testing Library is imported:
- if no "testing-library/module" set, then it's always considered as imported
- else, then it's considered as imported if "testing-library" import or custom module set within "testing-library/module" setting found
Why? To follow the philosophy discussed [here](https://github.com/testing-library/eslint-plugin-testing-library/issues/222#issuecomment-679592434) so by default the plugin is really aggressive to avoid missing code that should be reported. Then, if the plugin …
> Move rules settings to ESLint shared config: part 2 - check imports

- lib/detect-testing-library-utils.ts
- tests/create-testing-library-rule.test.ts
- tests/lib/rules/consistent-data-testid.test.ts
- tests/lib/rules/no-container.test.ts
- tests/lib/rules/no-debug.test.ts
- tests/lib/rules/no-multiple-assertions-wait-for.test.ts
- tests/lib/rules/no-node-access.test.ts
- tests/lib/rules/no-render-in-setup.test.ts
- tests/lib/rules/no-side-effects-wait-for.test.ts
- tests/lib/rules/prefer-find-by.test.ts
- tests/lib/rules/render-result-naming-convention.test.ts
- tests/lib/test-utils.ts
- tsconfig.json
Third part which includes:
- checking file name in testing library detection so we only report desired files
- new setting to customize file name pattern for desired reported files. It defaults to `.(test|spec).(t|j)sx?` (same as jest)
- new RuleTester for Testing Library which makes sure valid and invalid test cases have default config (just file name for now)
- common parserOptions for tests updated
With this PR we already have 2/3 necessary settings for v4: module where testing library utils can be imported and file name pattern for desired reported files. The final one will be the setting for customizing other methods than `render` to be considered as Testing Library render (e.g. `renderWithRedux`, `setUp`).
We are missing also the "aggressive reporting" mode for …
> Move rules settings to ESLint shared config: part 3 - check reported file name

- lib/detect-testing-library-utils.ts
- lib/node-utils.ts
- lib/rules/no-container.ts
- lib/rules/no-dom-import.ts
- lib/rules/no-manual-cleanup.ts
- tests/fake-rule.ts
- tests/lib/rules/no-manual-cleanup.test.ts
6th part which includes:
-  refactor `no-manual-cleanup` rule to use custom rule creator + detection helpers
- extract some detection helpers for getting imported module name related to Testing Library (either official or custom modules)
- improve rule to detect custom module from settings
> Move rules settings to ESLint shared config: part 5 - refactor no-manual-cleanup rule

- docs/rules/prefer-user-event.md
- lib/detect-testing-library-utils.ts
- lib/node-utils.ts
- lib/rules/prefer-user-event.ts
- tests/lib/rules/prefer-user-event.test.ts
refactor draft to include all the changes from #198 
this should make all the current scenarios and tests to pass, using the new helpers instead. What's pending:
- add tests with custom import libraries (the new ability from v4)
- add tests scenarios with `const { fireEvent } = require('module')` (the original implementation was not considering it, but now should be easier)
- add tests scenarios with `const rtl= require('module'); rtl.fireEvent()` (the original implementation was not considering it, but now should be easier)
I gotta say the rule's code is cleaner now 🎉 🚀
> feat: add new settings for prefer-user-event

- .lintstagedrc
- lib/detect-testing-library-utils.ts
- lib/node-utils.ts
- lib/rules/prefer-presence-queries.ts
- lib/utils.ts
- package.json
- tests/create-testing-library-rule.test.ts
- tests/fake-rule.ts
- tests/lib/rules/prefer-presence-queries.test.ts
This refactor for `prefer-presence-queries` includes:
- improve existing tests to check column where the error is reported
- add new detection helpers to determine if a node corresponds to `getBy*`, `queryBy*` or sync queries
- extract detection helpers to determine if a node corresponds to presence/absence assertion
> Move rules settings to ESLint shared config: refactor prefer-presence-queries rule

- lib/detect-testing-library-utils.ts
This PR includes two refactors related to detection helpers:
- declare detection helpers as standalone functions rather than object properties (so we avoid missing types if called with `this`)
- rename boolean functions to follow proper convention for boolean statements (prefixed by `is`, `has`, `should` or `can`)
> refactor: detection helpers tweaks

- lib/node-utils.ts
- lib/rules/await-async-query.ts
- lib/rules/await-async-utils.ts
- lib/rules/await-fire-event.ts
- lib/rules/no-await-sync-events.ts
- lib/rules/no-container.ts
- lib/rules/no-debug.ts
- lib/rules/no-multiple-assertions-wait-for.ts
- lib/rules/no-node-access.ts
- lib/rules/no-promise-in-fire-event.ts
- lib/rules/no-render-in-setup.ts
- lib/rules/no-side-effects-wait-for.ts
- lib/rules/no-wait-for-empty-callback.ts
- lib/rules/prefer-explicit-assert.ts
- lib/rules/prefer-find-by.ts
- lib/rules/prefer-screen-queries.ts
- lib/rules/prefer-user-event.ts
- lib/rules/prefer-wait-for.ts
- lib/rules/render-result-naming-convention.ts
Closes #253 
It seems there are no [further utils](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/experimental-utils/src/ast-utils/predicates.ts) than the two above. I guess they will add it over time, so we should keep an eye on it 🙂
> refactor(ast-utils): migrate custom node-utils to ASTUtils

- lib/rules/prefer-explicit-assert.ts
- tests/lib/rules/prefer-explicit-assert.test.ts
This PR fixes an issue with the `prefer-explicit-assert` `assertion` configuration option. If `assertion` is defined, it currently assumes all `getBy*` queries are wrapped in an `expect`. However, even with the `perfer-explicit-assert` there are valid uses that aren't wrapped in an `expect`:
```js
fireEvent.click(getByText('bar'));
const el = getByText('foo');
```
> fix(prefer-explicit-assert): handle getBy* without expect

- docs/rules/prefer-wait-for.md
- lib/detect-testing-library-utils.ts
- lib/node-utils.ts
- lib/rules/prefer-wait-for.ts
- tests/create-testing-library-rule.test.ts
- tests/fake-rule.ts
- tests/lib/rules/prefer-wait-for.test.ts
#198 migrating prefer-wait-for
I had to reimplement the rule because the implementation was tightly coupled with the imports
- I added support for `require`
- I improved the test coverage, I took all the existing scenarios and I added testing with `require`, with `settings` and all known imports for testing-library
- I improved the docs with the `require` support
> refactor: prefer-wait-for with the new settings

- docs/rules/await-async-query.md
- docs/rules/await-async-utils.md
- lib/detect-testing-library-utils.ts
- lib/node-utils.ts
- lib/rules/await-async-query.ts
- lib/rules/await-async-utils.ts
- tests/lib/rules/await-async-query.test.ts
- tests/lib/rules/await-async-utils.test.ts
This refactor for `await-async-utils` includes:
- using custom rule creator +  detection helpers
- extracting `Promise.all` and `Promise.allSettled` to common util when checking if promise is handled
- covering new case to report wrapper functions returning promise from async util (same as `await-async-query`)
> Move rules settings to ESLint shared config: refactor await-async-utils

- docs/rules/no-promise-in-fire-event.md
- lib/node-utils.ts
- lib/rules/no-promise-in-fire-event.ts
- tests/lib/rules/await-async-utils.test.ts
- tests/lib/rules/no-promise-in-fire-event.test.ts
This refactor for `no-promise-in-fire-event` includes:
- covering new case to report promises references from variables
> Move rules settings to ESLint shared config: refactor no-promise-in-fire-event

- lib/rules/no-wait-for-snapshot.ts
- tests/lib/rules/no-wait-for-snapshot.test.ts
This PR migrates the `no-wait-for-snapshot` rule to use the new helper, as part of #198
> refactor: migrate no-wait-for-snapshot to v4

- lib/detect-testing-library-utils.ts
- lib/rules/prefer-find-by.ts
- tests/create-testing-library-rule.test.ts
- tests/fake-rule.ts
- tests/lib/rules/prefer-find-by.test.ts
This PR migrates the `prefer-find-by` rule to use the new helper, as  part of #198
Fortunately, the rule was not even checking the imports, so only a few changes were required.
I did update the tests a bit so they are more "realistic" than just code floating around.
> refactor: migrate prefer-find-by to v4

- docs/rules/prefer-explicit-assert.md
- lib/rules/prefer-explicit-assert.ts
- tests/lib/rules/prefer-explicit-assert.test.ts
- Move `prefer-explicit-assert` to ESLint shared configuration
- Remove custom query option as aggressive reporting will be enabled by default
- Added more extensive test cases: when the user configures a custom module and cover all queries
For #269, I'll add this change in another PR 🙂
> refactor(prefer-explicit-assert): use new utils and remove custom query option

- .travis.yml
- CONTRIBUTING.md
- README.md
- lib/utils.ts
Rename references to default branch which now is `main`.
If you have a local clone, you can update it by running:
```
git branch -m master main
git fetch origin
git branch -u origin/main main
```
> chore: rename references to default branch

- lib/node-utils.ts
- lib/rules/no-await-sync-query.ts
- tests/lib/rules/no-await-sync-query.test.ts
Fixes #276 
@jeblackburn I had to fix this on v4 since most of the utils necessary for it were implemented in this next release.
> fix(no-await-sync-query): avoid reporting queries if not within callee

- lib/detect-testing-library-utils.ts
- lib/rules/render-result-naming-convention.ts
- tests/create-testing-library-rule.test.ts
- tests/fake-rule.ts
- tests/lib/rules/render-result-naming-convention.test.ts
I'm back 😎 Let's get v4 finished!
This PR includes:
- new `testing-library/custom-renders` shared setting to config custom render methods
- new `isRenderUtil` helper to detect `render` methods related to Testing Library + Aggressive Render Reporting
- tests for `render` detection within fake rule
- refactor `render-result-naming-convention` to use custom rule creator + detection helper
- fix some rule tests (some valid cases are invalid now due to Aggressive Render Reporting)
- remove `renderFunctions` rule option in favor of the new shared setting included
> Move rules settings to ESLint shared config: Aggressive Render Reporting + refactor render-result-naming-convention

- lib/detect-testing-library-utils.ts
- lib/node-utils.ts
- lib/rules/await-async-utils.ts
- lib/rules/no-promise-in-fire-event.ts
- lib/rules/no-wait-for-snapshot.ts
- lib/rules/render-result-naming-convention.ts
- tests/create-testing-library-rule.test.ts
- tests/fake-rule.ts
- tests/lib/rules/await-async-query.test.ts
- tests/lib/rules/await-async-utils.test.ts
- tests/lib/rules/await-fire-event.test.ts
- tests/lib/rules/no-await-sync-query.test.ts
- tests/lib/rules/no-dom-import.test.ts
- tests/lib/rules/no-manual-cleanup.test.ts
- tests/lib/rules/no-node-access.test.ts
- tests/lib/rules/no-promise-in-fire-event.test.ts
- tests/lib/rules/no-wait-for-snapshot.test.ts
- tests/lib/rules/prefer-explicit-assert.test.ts
- tests/lib/rules/prefer-presence-queries.test.ts
- tests/lib/rules/prefer-user-event.test.ts
- tests/lib/rules/prefer-wait-for.test.ts
Pull Request not related to any particular rule. The purpose of this PR is to fix some checks, extract some commons patterns and general improvements:
- Rename `testing-library/module` setting to `testing-library/utils-module`
- Move detection helpers types to simplify their definitions
- Add new `getReferenceNode` and `getPropertyIdentifierNode` node util methods
- Rename `getIdentifierNode` to `getDeepestIdentifierNode` to avoid any misunderstanding with its behavior
- Add `isTestingLibraryUtil` method to extract common logic from `isAsyncUtil` and `isRenderUtil`
- Check inside `isAsyncUtil` if coming from Testing Library or not
- Improve how `isNodeComingFromTestingLibrary` obtained node identifier so it detects chained properties correctly
- Refactor rules using …
> refactor: several tweaks

- lib/detect-testing-library-utils.ts
- lib/node-utils.ts
- lib/rules/render-result-naming-convention.ts
- tests/create-testing-library-rule.test.ts
- tests/lib/rules/prefer-wait-for.test.ts
- tests/lib/rules/render-result-naming-convention.test.ts
As mentioned in [the PR for migrating `render-result-naming-convention` rule to the new mechanism](https://github.com/testing-library/eslint-plugin-testing-library/pull/280#discussion_r585942050), this new PR aims to check nested/wrapped render calls.
After doing so, I came up with checking misleading renamed imports like:
```javascript
import { render as testingLibrary } from '@testing-library/react'
import { render } from 'somewhere-else'
// ...
// this render must not be reported when aggressive reporting is disabled
render()
```
It turned out we were reporting this case, so I've refined the "is coming from Testing Library" check to make sure the renamed import is what we are looking for. It was based on @gndelia's check for `fireEvent` but extracted into few utils and …
> refactor(render-result-naming-convention): refine checks to decide if coming from Testing Library

- lib/detect-testing-library-utils.ts
- lib/rules/prefer-screen-queries.ts
- tests/lib/rules/prefer-screen-queries.test.ts
This refactor for `prefer-screen-queries` includes:
- detect only queries coming from valid renders
- minor tweaks and fixes
I had an idea to simplify the whole rule implementation. However, since this one works fine, I'll leave it for now as I don't have that amount of time to spend on this.
> Move rules settings to ESLint shared config: refactor prefer-screen-queries rule

- lib/detect-testing-library-utils.ts
- lib/rules/no-wait-for-empty-callback.ts
- lib/utils.ts
- tests/lib/rules/no-wait-for-empty-callback.test.ts
This refactor for `no-wait-for-empty-callback` includes:
- improving `isAsyncUtil` detection
- minor tweaks and fixes
> Move rules settings to ESLint shared config: refactor no-wait-for-empty-callback

- docs/rules/no-debug.md
- lib/detect-testing-library-utils.ts
- lib/node-utils.ts
- lib/rules/no-debug.ts
- tests/lib/rules/no-debug.test.ts
This refactor for `no-debug` includes:
- improve test coverage and errors assertions
> Move rules settings to ESLint shared config: refactor no-debug rule 

- docs/rules/no-container.md
- lib/detect-testing-library-utils.ts
- lib/node-utils.ts
- lib/rules/no-container.ts
- lib/rules/no-debug.ts
- lib/rules/render-result-naming-convention.ts
- tests/lib/rules/no-container.test.ts
- tests/lib/rules/no-debug.test.ts
This refactor for `no-container` includes:
- improve location of the node reported
- improve test coverage and errors assertions
- add ability to detect `container` usage coming from functions wrapping `render`
- `no-debug`: add ability to detect `debug` usage coming from functions wrapping `render`
Ideally, the ability to detect functions wrapping a _reportable_ `render` should be part of `isRenderUtil`, or extracted into some helper. However, I'm gonna replicate the same behavior I applied in this PR (and others previously) to detect wrappers around `render` for remaining rules. After v4 I'll spend more time trying to make that check generic.
> Move rules settings to ESLint shared config: refactor no-container rule 

- lib/rules/no-await-sync-events.ts
- tests/lib/rules/no-await-sync-events.test.ts
Added exception for the new API proposed in https://github.com/testing-library/user-event/pull/581
Note that with the change `userEvent.type` (and `userEvent.keyboard`) will actually return no Promise if the `delay` is not `>0` so that the typing and the actual return value will match.
Further it might be worth discussing if this rule should be disabled for `.ts` and `.tsx` files as `ts(80007)` and `@typescript-eslint/await-thenable` already warn here and curating a manual list has no benefits when there already are warnings based on the type.
> fix: add no-await-sync-events exception for userEvent.keyboard

- lib/detect-testing-library-utils.ts
- tests/create-testing-library-rule.test.ts
- tests/lib/rules/no-await-sync-query.test.ts
- tests/lib/rules/no-dom-import.test.ts
- tests/lib/rules/no-manual-cleanup.test.ts
- tests/lib/rules/no-node-access.test.ts
Remove everything related to mechanism for matching files to be reported, as discussed in #296 
@MichaelDeBoey adding you here in case you want to double-check it too!
> refactor: remove mechanism to match files to be reported

- docs/rules/no-render-in-setup.md
- lib/node-utils.ts
- lib/rules/no-debug.ts
- lib/rules/no-render-in-setup.ts
- lib/rules/render-result-naming-convention.ts
- tests/lib/rules/no-render-in-setup.test.ts
This refactor for `no-render-in-setup` includes:
- updating rule doc and error message
- improving location of the node reported
- improving test coverage and errors assertions
- removing unused old AST util
- small fixes in other rules
> Move rules settings to ESLint shared config: refactor no-render-in-setup rule

- docs/rules/no-await-sync-events.md
- lib/detect-testing-library-utils.ts
- lib/rules/no-await-sync-events.ts
- lib/utils.ts
- tests/create-testing-library-rule.test.ts
- tests/fake-rule.ts
- tests/lib/rules/no-await-sync-events.test.ts
Finally, the last rule refactored! 😭 
This refactor for `no-await-sync-events` includes:
- new helper for detecting `userEvent` methods and imports
- reporting `userEvent` `type` and `keyboard` with 0 delay
- improving the location of the node reported
- improving test coverage and errors assertions
> Move rules settings to ESLint shared config: refactor no-await-sync-events rule

- lib/rules/prefer-user-event.ts
- tests/lib/rules/prefer-user-event.test.ts
> fix(prefer-user-event): format list of userEvent methods correctly 

- .github/workflows/pipeline.yml
- docs/migrating-to-v4-guide.md
Relates to #186 
Pinging @CreativeTechGuy since was who reported the issue which motivated this mechanism, and @MichaelDeBoey since we had several chats recently about how all this config works.
> docs: add guide for migrating to v4

- lib/detect-testing-library-utils.ts
- lib/rules/no-node-access.ts
- tests/lib/rules/no-node-access.test.ts
> fix(no-node-access): skip reporting files without Testing Library import

- README.md
> docs: update README with more info around Aggressive Reporting

- lib/node-utils/index.ts
- lib/node-utils/is-node-of-type.ts
Since all these functions are doing almost exactly the same, I extracted `isNodeOfType` and put all these kind of functions in a separate file.
@timdeschryver can probably help to make `isNodeOfType` more type-safe so we don't have to pass `NodeOfType` type anymore and we can do
```ts
export const isArrayExpression = isNodeOfType(AST_NODE_TYPES.ArrayExpression);
```
but I can't find it working atm.
> refactor(node-utils): extract `isNodeOfType` functions

- docs/rules/prefer-screen-queries.md
- lib/detect-testing-library-utils.ts
- lib/rules/prefer-screen-queries.ts
- tests/lib/rules/prefer-screen-queries.test.ts
> fix(prefer-screen-queries): avoid reporting custom queries

- README.md
- docs/migrating-to-v4-guide.md
- lib/detect-testing-library-utils.ts
- tests/create-testing-library-rule.test.ts
- tests/lib/rules/await-async-query.test.ts
- tests/lib/rules/no-await-sync-query.test.ts
- tests/lib/rules/prefer-screen-queries.test.ts
- tests/lib/rules/render-result-naming-convention.test.ts
> feat: new Aggressive Reporting settings

- tests/__snapshots__/index.test.ts.snap
- tests/index.test.ts
Took some inspiration from `eslint-plugin-jest` (see https://github.com/jest-community/eslint-plugin-jest/blob/main/src/__tests__/rules.test.ts).
With these tests, we ensure that
- all rules have docs
- all rules have tests
- all configs are referencing existing rules
> test: add extra tests

- lib/detect-testing-library-utils.ts
- lib/rules/no-debug.ts
- tests/lib/rules/no-debug.test.ts
closes #327
I intentionally left out the following scenario
```js
const { debug } = console
debug()
```
because it goes against the first invalid tests that against any `debug()`, it raises a flag.
> fix: allow console.debug() in no-debug

- README.md
Two new badges added:
- eslint-remote-tester status
- snyk package health status
You can preview the new badges [here](https://github.com/testing-library/eslint-plugin-testing-library/blob/new-badges/README.md)
> docs: add new badges to README

- lib/rules/no-wait-for-side-effects.ts
- tests/lib/rules/no-wait-for-side-effects.test.ts
Closes https://github.com/testing-library/eslint-plugin-testing-library/issues/351
> fix(no-wait-for-side-effects): catch implicit arrow function return

- lib/rules/no-wait-for-side-effects.ts
When looking at #363, I saw this part could be simplified
> refactor(no-wait-for-side-effects): simplify `reportSideEffects`

- docs/rules/no-wait-for-side-effects.md
- lib/create-testing-library-rule/detect-testing-library-utils.ts
- lib/node-utils/is-node-of-type.ts
- lib/rules/no-wait-for-side-effects.ts
- tests/lib/rules/no-wait-for-side-effects.test.ts
Closes https://github.com/testing-library/eslint-plugin-testing-library/issues/360
We should decide how we want to release this enhancement. Seems like the discussion is centered around:
a) minor version bump without an option
b) minor version bump with an option, which is off by default
Also, I've noticed this rule is NOT reporting this case. Is that intentional? 🤔 
```
await waitFor(() => {
userEvent.click(button) // reported
const a = userEvent.click(button) // NOT reported
})
```
> feat(no-wait-for-side-effects): report render in waitFor

- lib/rules/await-async-query.ts
- tests/lib/rules/await-async-query.test.ts
> fix(await-async-query): get correct Identifier related to CallExpression

- lib/rules/prefer-screen-queries.ts
- tests/lib/rules/prefer-screen-queries.test.ts
> feat(prefer-screen-queries): detect render in wrappers correctly

- README.md
- docs/semantic-versioning-policy.md
> docs: add semantic versioning policy

- docs/rules/prefer-user-event.md
- lib/create-testing-library-rule/detect-testing-library-utils.ts
- lib/rules/prefer-user-event.ts
- tests/lib/rules/prefer-user-event.test.ts
closes #261   
It's been a while since the last time I worked in rules here and with eslint/AST. I was a bit out of shape 🤣  so it took me more than I originally expected. Any feedback is appreciated!
> feat: add support for fireEvent as function in prefer-user-event

- docs/rules/no-unnecessary-act.md
- lib/rules/no-unnecessary-act.ts
- tests/lib/rules/no-unnecessary-act.test.ts
Closes https://github.com/testing-library/eslint-plugin-testing-library/issues/382
> feat: isStrict option for no-unnecessary-act

- .github/stale.yml
The stale bot is trying to close issues flagged as bugs. I think we should prevent this and leave them open until we can handle them.
> chore: prevent stalebot to close issues flagged as bug

- README.md
- Use HTTPS for link to ESLint homepage
It's a good idea to use HTTPS where possible.
> docs: use HTTPS for link to ESLint homepage

- lib/rules/no-unnecessary-act.ts
- tests/lib/rules/no-unnecessary-act.test.ts
Closes https://github.com/testing-library/eslint-plugin-testing-library/issues/416
Everything that is reported with `isStrict` disabled should also be reported with `isStrict` enabled. That's what this PR fixes.
With regards to tests - went with the quickest approach. Shamelessly copy-pasted test cases and enabled `isStrict` 😄 If we have a better way to deal with this duplication - let me know.
> fix(no-unnecessary-act): report everything that's reported in non-strict

- lib/rules/no-unnecessary-act.ts
After some thinking I came to the conclusion that `shouldBeReported` can be simplified
> refactor(no-unnecessary-act): simplify `checkNoUnnecessaryActFromBlockStatement`'s `shouldBeReported` assigning

- README.md
- Add a full stop `.` to the `eslintrc` filename
All other uses of `.eslintrc` have the full stop, this one was missing it.
> docs: add full stop before eslintrc filename

- .github/ISSUE_TEMPLATE/bug_report.yml
- Create bug report form
Work in progress.
Go to https://github.com/HonkingGoose/eslint-plugin-testing-library/blob/patch-2/.github/ISSUE_TEMPLATE/bug_report.yml to see a rendered preview of the bug report form.
Helps with issue #400, but doesn't close it as we want forms for other things as well. 😉 
> - Ideally we would have other issue forms to propose a new rule, to request a rule change, or to request a general change.
**GItHub docs for the Issue Form:**
- [Syntax for issue forms](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms)
- [Syntax for GitHub's form schema](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-githubs-form-schema)
> chore: create bug report form

- .github/ISSUE_TEMPLATE/propose_new_rule.yml
- Create the form that contributors can use to propose a new rule
Go to https://github.com/HonkingGoose/eslint-plugin-testing-library/blob/chore/430-propose-new-rule-form/.github/ISSUE_TEMPLATE/propose_new_rule.yml to see a preview of the template.
You can click one of the checkboxes in issue #430 after you've merged this.
> chore: create propose new rule form

- .github/ISSUE_TEMPLATE/request_rule_change.yml
- Create request general change form
Go to https://github.com/HonkingGoose/eslint-plugin-testing-library/blob/chore/430-request-a-rule-change/.github/ISSUE_TEMPLATE/request_rule_change.yml to see the preview.
Helps with #430.
You can click another checkbox after this PR is merged.
> chore: create request rule change form

- .github/ISSUE_TEMPLATE/config.yml
- Block empty issues
- Redirect issues that should go to upstream ESLint project
- Add link to our discussions page on GitHub
Fixes #431.
**EDIT:** Now that I have created the PRs for the Issue Forms, it makes more sense to wait until those 3 Issue Form PRs have been merged into `main`, and then review and merge this PR.
> chore: configure GitHub template chooser

- docs/rules/prefer-explicit-assert.md
- lib/rules/prefer-explicit-assert.ts
- tests/lib/rules/prefer-explicit-assert.test.ts
A recent patch implemented matching `findBy*` queries by the
`prefer-explicit-assert` rule. This patch makes it possible to disable it
in cases where it's too distracting.
This adds an option so that a user can globally disable that findBy queries are checked by the role.
Fixes #449
> feat: Add an option to remove the matching of findBy queries by the prefer-explicit-assert rule

- package.json
As said in https://github.com/testing-library/eslint-plugin-testing-library/pull/456#issuecomment-903276903, `ts-jest` doesn't apply SemVer, so we should make it an exact version
https://github.com/kulshekhar/ts-jest#versioning
> chore(devDeps): make `ts-jest`'s version exact

- CONTRIBUTING.md
- README.md
- docs/rules/no-debugging-utils.md
- lib/configs/angular.ts
- lib/configs/react.ts
- lib/configs/vue.ts
- lib/rules/no-debugging-utils.ts
- tests/__snapshots__/index.test.ts.snap
- tests/lib/rules/no-debugging-utils.test.ts
Closes #467
BREAKING CHANGE: `no-debug` is now called `no-debugging-utils`
> feat(no-debug): rename to `no-debugging-utils`

- lib/rules/prefer-explicit-assert.ts
- package.json
- tests/lib/rules/prefer-explicit-assert.test.ts
- Check some properties' existence instead of just assuming they always exist.
Fixes #475
> fix(prefer-explicit-assert): check property existence

- .github/ISSUE_TEMPLATE/request_rule_change.yml
- Improve the template for request rule change to reference an existing change rather than a new one.
There was no issue open for this.
> chore: improve template for request rule change

- lib/rules/render-result-naming-convention.ts
- Use disjunction to separate allowed render result names
Separate allowed render result names by comma and an "or" before the last one.
Before:
```
`wrapper` is not a recommended name for `render` returned value. Instead, you should destructure it, or name it using one of: `view`, `utils`
```
After:
```
`wrapper` is not a recommended name for `render` returned value. Instead, you should destructure it, or name it using one of: `view`, or `utils`
```
> Use disjunction to separate allowed render result names

- docs/rules/no-unnecessary-act.md
Tweak docs to reflect `isStrict` option on `no-unnecessary-act` being enabled by default
I've noticed https://github.com/testing-library/eslint-plugin-testing-library/pull/479 didn't change docs to reflect default `isStrict` option.
> docs(no-unnecessary-act): isStrict is enabled by default

- lib/rules/prefer-find-by.ts
- tests/lib/rules/prefer-find-by.test.ts
- No longer report invalid usages with a missing query method.
- Add a test covering the code changes.
Fixes #501
> fix(prefer-find-by): fix report with querySelector

- tests/index.test.ts
`generateConfigs()` function executes a nodejs [exec] that takes many
seconds to complete. As the test was not waiting for the process to
terminate, Jest was complaining with the following error message:
```
Jest did not exit one second after the test run has completed.
This usually means that there are asynchronous operations that weren't stopped in your tests. Consider running Jest with `--detectOpenHandles` to troubleshoot this issue.
```
Additionally, this test could have a false positive expectation since it
was likely to run the snapshot comparison with previously generated
plugin configurations.
By default Jest tests will timeout if they take longer than 5 seconds to
complete, since this test takes more than 10 seconds to complete on my
local machine, this test timeout …
> test: wait for async process completion

- lib/node-utils/is-node-of-type.ts
- package.json
Now that https://github.com/typescript-eslint/typescript-eslint/pull/4503 is merged & released, we can get rid of our own version of `isNodeOfType`
> fix: use `ASTUtils`'s `isNodeOfType` instead of own version

- docs/rules/prefer-presence-queries.md
- lib/rules/prefer-presence-queries.ts
- tests/lib/rules/prefer-presence-queries.test.ts
- Added configuration options to `testing-library/prefer-presence-queries` to enable or disable just the presence/absence checks by themselves;
- I started out trying to implement the check for `within`, but I think I'd have to do a lot more reading about eslint before I can tackle that, whereas this configuration-based change was a lot simpler. I do have a stash with some changes based on that, but I'm unlikely to get to them soon.
Provides a patch for #518 (without entirely fixing it).
> feat(prefer-presence-queries): add `absence` & `presence` options

- lib/rules/no-global-regexp-flag-in-query.ts
- tests/lib/rules/no-global-regexp-flag-in-query.test.ts
- check if the `namePropertyNode` var exists since it can be `undefined`.
Closes #565
> fix(no-global-regexp-flag-in-query): check if empty name property node

- README.md
- docs/rules/no-await-sync-events.md
- lib/rules/no-await-sync-events.ts
- tests/lib/rules/no-await-sync-events.test.ts
- Adding `eventModules` option to be able to disable reporting "fire-event" or "user-event"
Closes #567
> feat(no-await-sync-events): add eventModules option

- lib/rules/no-await-sync-events.ts
- tests/lib/rules/no-await-sync-events.test.ts
- Define `eventModules` option schema correctly (array of enum instead of just enum)
Relates to https://github.com/testing-library/eslint-plugin-testing-library/pull/569#discussion_r847850631
> fix(no-await-sync-events): define option schema correctly

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/propose_new_rule.yml
- .github/ISSUE_TEMPLATE/request_general_change.yml
- .github/ISSUE_TEMPLATE/request_rule_change.yml
- .github/stale.yml
- MAINTAINERS.md
- Update stale bot conditions
- Assign "triage" label to new issues
- Add `MAINTAINERS.md` file
> chore: improve triage process

- tests/create-testing-library-rule.test.ts
- tests/lib/rules/await-async-query.test.ts
- tests/lib/rules/await-async-utils.test.ts
- tests/lib/rules/await-fire-event.test.ts
- tests/lib/rules/no-await-sync-query.test.ts
- tests/lib/rules/no-container.test.ts
- tests/lib/rules/no-debugging-utils.test.ts
- tests/lib/rules/no-dom-import.test.ts
- tests/lib/rules/no-node-access.test.ts
- tests/lib/rules/no-promise-in-fire-event.test.ts
- tests/lib/rules/no-render-in-setup.test.ts
- tests/lib/rules/no-unnecessary-act.test.ts
- tests/lib/rules/no-wait-for-empty-callback.test.ts
- tests/lib/rules/no-wait-for-multiple-assertions.test.ts
- tests/lib/rules/no-wait-for-side-effects.test.ts
- tests/lib/rules/no-wait-for-snapshot.test.ts
- tests/lib/rules/prefer-find-by.test.ts
- tests/lib/rules/prefer-query-by-disappearance.test.ts
- tests/lib/rules/prefer-screen-queries.test.ts
- tests/lib/rules/render-result-naming-convention.test.ts
Follow-up of #572.
All rules that are included in the `marko` config should test that the rule is working for `@marko/testing-library` as well.
To do so for #572, @PrashantAshok copied over some tests and replaced the import, but didn't include tests for the following rules:
- `await-async-utils`
- `no-promise-in-fire-event`
- `no-render-in-setup`
- `no-wait-for-snapshot`
- `prefer-find-by`
The way I presented in the PR, is to map over an array of the already tested framework + `@marko/testing-library`.
This PR is only doing that.
I'll create a separate PR to test against all testing framework that the rules support.
> test: refactor `@marko/testing-library` tests

- lib/rules/no-dom-import.ts
- tests/lib/rules/await-async-query.test.ts
- tests/lib/rules/await-async-utils.test.ts
- tests/lib/rules/no-await-sync-query.test.ts
- tests/lib/rules/no-container.test.ts
- tests/lib/rules/no-debugging-utils.test.ts
- tests/lib/rules/no-dom-import.test.ts
- tests/lib/rules/no-node-access.test.ts
- tests/lib/rules/no-promise-in-fire-event.test.ts
- tests/lib/rules/no-render-in-setup.test.ts
- tests/lib/rules/no-wait-for-empty-callback.test.ts
- tests/lib/rules/no-wait-for-multiple-assertions.test.ts
- tests/lib/rules/no-wait-for-side-effects.test.ts
- tests/lib/rules/no-wait-for-snapshot.test.ts
- tests/lib/rules/prefer-find-by.test.ts
- tests/lib/rules/prefer-query-by-disappearance.test.ts
- tests/lib/rules/prefer-screen-queries.test.ts
- tests/lib/rules/render-result-naming-convention.test.ts
Follow-up of #582 & #583
Added explicit tests for `@testing-library/angular`
> test: refactor `@testing-library/angular` tests

- tests/lib/rules/no-await-sync-events.test.ts
- tests/lib/rules/no-promise-in-fire-event.test.ts
- tests/lib/rules/no-render-in-setup.test.ts
- tests/lib/rules/prefer-find-by.test.ts
Follow-up of #582, #583, #584, #585 & #587
> test: cleanup tests

- docs/rules/no-node-access.md
- lib/rules/no-node-access.ts
- tests/lib/rules/no-node-access.test.ts
- Add `allowContainerFirstChild` option to `no-node-access` rule
Fixes #593
> feat(no-node-access): add `allowContainerFirstChild` option

- lib/rules/prefer-query-by-disappearance.ts
- tests/lib/rules/prefer-query-by-disappearance.test.ts
- refactor reporting an error deeper, where the `get` or `find` query variants are found
- refactor some function names to convey that they also check/report the error, not just return boolean based on if an error should be reported
- update unit tests to have correct error line and column
Closes #600
> fix: `prefer-query-by-disappearance` error line and column to the beginning of `get` or `find` queries

- lib/rules/no-await-sync-events.ts
- tests/lib/rules/no-await-sync-events.test.ts
- Check if `delay` is declared or assigned a value elsewhere than in the call expression's arguments
- Add test cases that have declarations and assignments
Closes #403
> fix: `no-await-sync-events` false positive

- docs/rules/consistent-data-testid.md
- lib/rules/consistent-data-testid.ts
- tests/lib/rules/consistent-data-testid.test.ts
In the discussion of the issue #509 there hasn't been a consensus how to fix the issue, and this is my suggestion.
It seems that the crash in 509 is caused by several repos using static site generators and their dynamic routing.
- `gatsbyjs/gatsby` uses Gatsby.js
- [`vickev/howdypix`](https://github.com/vickev/howdypix/tree/master/apps/webapp) [uses Next.js](https://github.com/vickev/howdypix/blob/master/apps/webapp/package.json#L71)
Both [Gatsby.js](https://www.gatsbyjs.com/docs/reference/routing/file-system-route-api/#syntax-client-only-routes) and [Next.js](https://nextjs.org/docs/routing/dynamic-routes) support square brackets and three periods in filename. However, since the three periods is optional, it makes sense to catch this edge case by looking only at the presence of square …
> fix(consistent-data-testid): avoid crash for filename with square brackets

- docs/rules/no-wait-for-side-effects.md
- lib/rules/no-wait-for-side-effects.ts
- tests/lib/rules/no-wait-for-side-effects.test.ts
- when reporting side efdects, check if the node is a `.then()`, and if it is, not report it
- added unit tests
- adds a mention of edge case to rule documentation
Closes: #500
> fix(no-wait-for-side-effects): false positive inside `.then()`

- lib/utils/index.ts
- tests/lib/rules/no-node-access.test.ts
- This PR adds childElementCount in no-node-access rule
```js
render(
<ul>
<li>item 1</li>
<li>item 1</li>
</ul>
);
expect(screen.getByRole('list').childElementCount).toBe(2);
```
> feat(no-node-access): report childElementCount prop

- docs/rules/no-dom-import.md
- lib/create-testing-library-rule/detect-testing-library-utils.ts
- lib/rules/no-dom-import.ts
- tests/lib/rules/no-dom-import.test.ts
- adds a new util function `getAllTestingLibraryImportNodes` to get all `testing-library` related imports
- in `no-dom-import` loop through all the `testing-library` imports, and report an error on that import(s) that imports from `testing-library/dom`
Closes #586 
P.S. If you feel that this PR is following the rules of [Hactoberfest](https://hacktoberfest.com/) and this gets merged, it would be wonderful if this PR would be tagged with a `hacktoberfest-accepted` tag/label. Thanks!
> fix(no-dom-imports): false negatives with several testing library imports

- docs/rules/no-node-access.md
- lib/rules/no-node-access.ts
- tests/lib/rules/no-node-access.test.ts
- checks if the node accessing property (e.g. `children`, `firstChild` or `previousSibling`) is called by `props`, so if there's a `props.children`, `props.firstChild` or `props.previousSibling`, then that code won't be reported as an error
Closes #386 (at least the most common case, not all of the examples given in that issue).
This PR does not close/fix the deconstructed props case (mentioned by @Belco90 in #386):
```
function ComponentB({ children }) {
// this should NOT be reported
if (children) {
// ...
}
// this should NOT be reported
return <div>{children}</div>
}
```
But I am happy to make another PR about this case too (I just haven't figured out how to identify with AST).
P.S. If you feel that this PR is following the rules of [Hactoberfest](https://hacktoberfest.com/) and this …
> fix(no-node-access): false positives with `props.children`

- lib/configs/angular.ts
- lib/configs/marko.ts
- lib/configs/react.ts
- lib/configs/vue.ts
- lib/rules/no-debugging-utils.ts
- tests/__snapshots__/index.test.ts.snap
BREAKING CHANGE: `no-debugging-utils` defaults to `warn` instead of `error`
- Change `no-debugging-utils` default to `warn` in shared configs instead of `error`
Resolves https://github.com/testing-library/eslint-plugin-testing-library/issues/622.
> feat(no-debugging-utils): default to warn instead of error

- docs/rules/no-debugging-utils.md
- lib/rules/no-debugging-utils.ts
- tests/lib/rules/no-debugging-utils.test.ts
BREAKING CHANGE: enable all debug methods by default for `no-debugging-utils`
- Enable all of the debug methods by default in the `no-debugging-utils` rule
Resolves https://github.com/testing-library/eslint-plugin-testing-library/issues/621
> feat(no-debugging-utils): enable all methods

- README.md
- docs/rules/no-await-sync-queries.md
- lib/configs/angular.ts
- lib/configs/dom.ts
- lib/configs/marko.ts
- lib/configs/react.ts
- lib/configs/vue.ts
- lib/rules/no-await-sync-queries.ts
- tests/__snapshots__/index.test.ts.snap
- tests/lib/rules/no-await-sync-queries.test.ts
BREAKING CHANGE: `no-await-sync-query` is now called `no-await-sync-queries`
---
Partially resolves #478 & #623
> feat(no-await-sync-query): rename to `no-await-sync-queries`

- lib/node-utils/index.ts
- lib/node-utils/is-node-of-type.ts
- lib/rules/await-async-events.ts
- tests/lib/rules/await-async-events.test.ts
- Improve the fixer for `await-async-events` to also add missing `async` keyword to wrapping function expression
Resolves https://github.com/testing-library/eslint-plugin-testing-library/issues/674
> fix(await-async-events): improve fixer

- lib/rules/no-wait-for-side-effects.ts
- tests/lib/rules/no-wait-for-side-effects.test.ts
- adds a new helper function that checks if there are side effects (`userEvent`, `fireEvent` or `render`) in variable declarations
- adds a new invalid unit test
Closes #368 
P.S. If you feel that this PR is following the rules of [Hactoberfest](https://hacktoberfest.com/) and this gets merged, it would be wonderful if this PR would be tagged with a hacktoberfest-accepted tag/label. Thanks!
> fix(no-wait-for-side-effects): false negatives in variables declarations

- lib/rules/no-global-regexp-flag-in-query.ts
- tests/lib/rules/no-global-regexp-flag-in-query.test.ts
- rename one rule-specific helper function
- add a rule-specific helper array to keep tab of variable declarations that have a global RegExp
- add detecting if the argument that is passed to a testing-library query has a global RegExp in its variable declaration
- add unit test with this scenario
Closes #592
P.S. If you feel that this PR is following the rules of [Hactoberfest](https://hacktoberfest.com/) and this gets merged, it would be wonderful if this PR would be tagged with a hacktoberfest-accepted tag/label. Thanks!
> feat(no-global-regexp-flag-in-query): Detect global RegExp in variable declarations

- docs/rules/prefer-find-by.md
- lib/rules/prefer-find-by.ts
- tests/lib/rules/prefer-find-by.test.ts
- change autofixer to keep wait query's second argument (options), previously this was lost in autofixing
- fixing documentation formatting (code keywords and a dot)
Solves half (part/scenario 1) of the issue #579
> fix(prefer-find-by): Autofix takes wait query's options into account

- tests/lib/rules/no-node-access.test.ts
These examples were gotten from discussions in issue #386
- add a valid test case to `no-node-access`
Not closing an existing issue, just adding one test that should have been added in #658. I commented in that PR that it wouldn't be fixing an error from a code like this (component with destructured props), but turns out, that this code hasn't produced an error, it is totally valid from this rule's perspective.
> test(no-node-access): add more valid test cases

- lib/node-utils/index.ts
- lib/rules/await-async-query.ts
- lib/rules/await-async-utils.ts
- lib/rules/await-fire-event.ts
- package.json
Will fix ESLint errors in #690
> chore: update dependencies

- docs/rules/no-render-in-setup.md
Add rationale to `no-render-in-setup` doc.
Fixes #696.
> docs: add rationale to no-render-in-setup

- .github/workflows/smoke-test.yml
- package.json
- chore(dev-deps): update eslint-remote-tester-repositories
- Updates `eslint-remote-tester-repositories` to new major version. No breaking changes. API is now considered as stable
- ci: fix smoke test's npm setup
- Workflow seemed to be crashing due to some Node/NPM setup issues. Copied setup steps from `pipeline.yml`
> ci: fix smoke test's npm setup

- lib/configs/index.ts
- lib/utils/types.ts
- tests/lib/rules/consistent-data-testid.test.ts
- tests/lib/rules/no-node-access.test.ts
- tests/lib/rules/no-unnecessary-act.test.ts
- tools/generate-configs/index.ts
- tools/generate-configs/utils.ts
- Fix new linting errors reported by eslint-plugin-import
Since we don't have our dependencies pinned, some ESLint plugin/config got updated and started reporting new errors in #722. I'm tired of this behavior, already happened many times. I'm pinning the dependencies in another PR and setting up Renovatebot.
> chore: fix new linting errors reported

- lib/rules/await-async-utils.ts
- tests/lib/rules/await-async-utils.test.ts
- Use early return via a condition `isAsyncUtilOrKnownAliasAroundIt` to reduce indentation
- Upon visiting `VariableDeclarator` nodes, detect destructured property aliases and assignments of known async wrapper functions
- Add `getMessageId` function
- Add test cases
Fixes #715
> fix(await-async-utils): false positive when destructuring

- lib/rules/await-async-utils.ts
- tests/lib/rules/await-async-utils.test.ts
- [x ] I have read the [contributing guidelines](https://github.com/testing-library/eslint-plugin-testing-library/blob/main/CONTRIBUTING.md).
- In `detectAsyncUtilWrapper`, adapt code to not push empty strings into `functionWrapperNames`.
Partially fixes #732 : Addresses the first example, but not the latter one.
> fix(await-async-util): false positives due to empty strings

- .github/workflows/pipeline.yml
- https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#concurrency
- https://github.blog/changelog/2021-04-19-github-actions-limit-workflow-run-or-job-concurrency
- > The fully-formed ref of the branch or tag that triggered the workflow run. For workflows triggered by `push`, this is the branch or tag ref that was pushed. For workflows triggered by `pull_request`, this is the pull request merge branch. For workflows triggered by `release`, this is the release tag created. For other triggers, this is the branch or tag ref that triggered the workflow run. This is only set if a branch or tag is available for the event type. The ref given is fully-formed, meaning that for branches the format is `refs/heads/<branch_name>`, for pull requests it is …
> chore: remove `styfle/cancel-workflow-action` usage

- jest.config.js
- package-lock.json
- package.json
- replace `ts-jest` with `@swc/jest`
Making our Jest tests faster with [`@swc/jest`](https://swc.rs/docs/usage/jest). A comparison running all the tests in an Intel MacBook Pro:
> chore(jest): replace `ts-jest` with `@swc/jest`

- .releaserc.json
- package-lock.json
- package.json
- Remove the `pkgRoot` from semantic-release config, so it points directly to the root of the repo instead of `dist/` folder.
Pointing to the root of the repo is the correct behavior. It was incorrect before, that's why we had to copy the extra files after building. By setting the `pkgRoot` to the root of the repo, and setting the proper `files` in the `package.json`, npm CLI and semantic-release will bundle and publish it as expected.
> chore(semantic-release): change package root

- lib/rules/await-async-events.ts
- tests/lib/rules/await-async-events.test.ts
* Skipping nodes named "setup" in the await-async-events rule
Fixes #800 
This is my first open source PR. I'd rather base the logic on the type of the call expression (is it a `Promise`?), but I don't believe that information is available in the AST so I just went off of the identifier name.
> fix(await-async-events): sync userEvent.setup() should not be reported

- docs/migration-guides/v6.md
Typo in the migration guide that's already fixed in the GitHub release.
The rules are called `no-await-sync-query` and `no-await-sync-queries`
https://github.com/testing-library/eslint-plugin-testing-library/releases/tag/v6.0.0
> docs: typo in v6 migration guide

- docs/rules/prefer-implicit-assert.md
> docs(prefer-implicit-assert): typos in docs

- lib/rules/no-manual-cleanup.ts
- tests/lib/rules/no-manual-cleanup.test.ts
Crawl all the import references when sniffing out `no-manual-cleanup` violations.
There is currently a bug with `no-manual-cleanup` where we only ever check the first import of any `testing-library` package. While duplicative imports of the _same_ package is very likely uncommon, there are many packages within the `testing-library` ecosystem that will trip up the package detection and break this rule when we only look at the first.
> fix: handle multiple imports with `no-manual-cleanup`

- lib/utils/index.ts
- tests/lib/rules/prefer-presence-queries.test.ts
React Native Testing Library recommend to use this eslint plugin: https://callstack.github.io/react-native-testing-library/docs/eslint-plugin-testing-library 
React Native Testing Library has custom matchers: https://callstack.github.io/react-native-testing-library/docs/jest-matchers#tobeonthescreen
this PR adding support for support for that matsher `toBeOnTheScreen`
```tsx
expect(screen.queryByText('button')).toBeOnTheScreen(); // No error :(
expect(screen.queryByText('button')).toBeInTheDocument(); // Error: testing-library/prefer-presence-queries
```
...
> feat(prefer-presence-queries): support react-native matcher `toBeOnTheScreen`

- README.md
I believe there is a mistake in the README, where the `s` should not be optional, but the `x` should
*.[jt]s?(x):
[jt]: Matches a single character, either 'j' or 't'.
s?: The 's' is optional.
(x): This matches an `x`, however, parenthesis are not a standard syntax for file globbing.
*.[jt]sx?:
[jt]: Matches a single character, either 'j' or 't'.
s: This 's' is required.
x?: The 'x' is optional.
File matching in eslint configuration example in the README file.
> docs: update eslint pattern matching

- docs/rules/prefer-screen-queries.md
- [ X] I have read the [contributing guidelines](https://github.com/testing-library/eslint-plugin-testing-library/blob/main/CONTRIBUTING.md).
I was going through this example to understand a failure I was getting. I noticed that the import methods from the testing-library was missing the `render` method. Not sure if that's intentional since the examples are for any testing library. Thanks!
> docs: add missing import

- .all-contributorsrc
- Avoid skipping CI in all-contributors PRs.
Since we have required status checks before merging PRs, all-contributors can't skip CI. Otherwise, the status checks will hang forever waiting to be run, blocking the PR from being merged.
> chore(all-contributors): disable skipping ci

- .github/workflows/verifications.yml
- Set up [Codecov](https://about.codecov.io/)
Enabling this tool to enforce a certain coverage threshold in our tests.
> chore: add codecov step

- lib/rules/no-await-sync-events.ts
- package-lock.json
- package.json
- tsconfig.json
- Upgrades TypeScript from v4.9 to v5.0 (we can't use v5.1 and above in Node.js v12)
- Updates `tsconfig.json` based on https://www.totaltypescript.com/tsconfig-cheat-sheet and the requirements of the project
Based on https://github.com/testing-library/eslint-plugin-testing-library/pull/856. See 4c2871616bd70fc2a032556429686476ae1169e7...0f6fe962b2897d0cb000666db3fa20619db9204b for changes.
- https://node.green/#ES2019
> chore: upgrade TypeScript to v5.0

- lib/rules/no-await-sync-events.ts
- tests/lib/rules/no-await-sync-events.test.ts
- Fix TS errors silenced with `@ts-expect-error`
These errors were silenced in #858
> refactor: fix ts-expect-error

- lib/node-utils/index.ts
- lib/rules/await-async-events.ts
- tests/lib/rules/await-async-events.test.ts
- tests/lib/rules/await-async-utils.test.ts
In `await-async-events`, `await-async-queries` and `await-async-utils` when determining whether a promise is handled the checks are performed on a parent expression that evaluates to the call expression returning a promise instead of always the call expression. In the following cases the parent expression is used instead.
```ts
// sequence expression
(sideEffect(), promise());
// conditional expression
condition ? promise() : otherPromise();
// logical expression
maybePromise() ?? promise();
maybePromise() || promise();
condition && promise();
```
This change does not eliminate false positives from the three `await-async-` rules. The rules are fundamentally written in a brittle way where they look for specific reasons not to report and default to reporting. This means the rules are not …
> fix(await-async-events): false positive reports on awaited expressions evaluating to promise

- lib/rules/await-async-events.ts
- tests/lib/rules/await-async-events.test.ts
The circuit-breaker checking for `userEvent.setup()` was executed after `detectEventMethodWrapper` so the circuit-breaking only applied to cases where the expression is not returned. It's intended to be applied generally so this PR moves it to the top of its code block.
My last contribution was received well so I picked another open issue.
Fixes #881
This is another false-positive where the root problem is defaulting to report unless a reason not to report is found. If new methods are introduced to `userEvent` the rule will assume they return promises. I'd like to change the behaviour to check for an allow-list of method names instead of checking it's not specifically `setup` so future bugs would be false negatives instead of false positives. I didn't do that in this PR because maybe it's …
> fix(await-async-events): false positives for userEvent.setup() returned

- CONTRIBUTING.md
- Update the [How to Contribute to an Open Source Project on GitHub](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) link that links to a 404 page with the correct URL.
> docs(contributing): fix broken link

- .eslint-doc-generatorrc.js
- README.md
- lib/configs/index.ts
- lib/index.ts
- tests/index.test.ts
- tools/generate-configs/index.ts
- Adds plugin name and version metadata (aka #921)
- Adds flat versions of configs, for ESLint v9
Resolves #902
Resolves #853
This uses a very similar approach to what I'm using for `eslint-plugin-jest` - the types should actually be pretty much correct, but I've just gone straight to casting since things are a bit of a mess right now ecosystem wise, which'll improve once we have everyone on ESLint v9.
Similarly I've not worried about adding any particular tests since the output is pretty stable and easily validated manually (which I have already), and I've based the documentation off what we use in `eslint-plugin-jest` too
> feat: add support for flat config

- tests/create-testing-library-rule.test.ts
- tests/lib/rules/no-await-sync-events.test.ts
- tests/lib/rules/no-debugging-utils.test.ts
- tests/lib/rules/no-wait-for-side-effects.test.ts
- tests/lib/rules/prefer-explicit-assert.test.ts
- tests/lib/rules/prefer-query-by-disappearance.test.ts
- tests/lib/rules/prefer-screen-queries.test.ts
- removed duplicate test cases
ESLint v9 now errors about duplicate test cases, meaning these have to be either removed or made unique - all of the cases being removed in this pull request are flat out code duplicates hence their removal; there are still other duplicates that will need addressing, but they're a little more fuzzy so I will tackle them in another pull request.
(this helps reduce the diff for #926 and friends)
> test: remove duplicate cases

- .github/workflows/release.yml
- .github/workflows/verifications.yml
Caching is  now done easily with `actions/setup-node` v4
> chore: remove `bahmutov/npm-install` usage

- lib/rules/no-manual-cleanup.ts
- tests/lib/rules/no-manual-cleanup.test.ts
- Changes `no-manual-cleanup` so it checks every import rather than just the first one
Currently the rule assumes the first `@testing-library` import will be one with a `cleanup`, which isn't true
> fix(no-manual-cleanup): properly check all `@testing-library` imports

- lib/node-utils/index.ts
- lib/rules/consistent-data-testid.ts
- lib/rules/no-debugging-utils.ts
- lib/rules/no-manual-cleanup.ts
- lib/rules/no-promise-in-fire-event.ts
- lib/rules/prefer-find-by.ts
- lib/utils/compat.ts
- lib/utils/index.ts
- introduced compat utilities that enable support for ESLint v9
- replaced usages of `context` functions that were removed in v9 in favor of compat utils
Resolves #924
Resolves #899
> fix: replace use of deprecated methods

- .github/workflows/verifications.yml
- package-lock.json
- package.json
- tests/lib/FlatCompatRuleTester.ts
- tests/lib/rules/await-async-events.test.ts
- tests/lib/rules/await-async-utils.test.ts
- tests/lib/rules/no-dom-import.test.ts
- tests/lib/rules/no-node-access.test.ts
- tests/lib/rules/prefer-find-by.test.ts
- tests/lib/rules/prefer-query-matchers.test.ts
- tests/lib/test-utils.ts
- introduces a new "flat compat" rule tester that accepts tests written for legacy config, and automatically converts them to flat config when running against ESLint v9
- this is a class I have used in `eslint-plugin-jest`, `eslint-plugin-jest-dom`, and `eslint-plugin-jest-extended` with great successful
- updates tests to pass when using ESLint v9
- updates CI to run test suite against ESLint v9
Before saying the plugin officially supports ESLint v9, it should be testing against v9 which in turn requires accounting for v9's defaulting to flat config and the improvements that have been made to the rule tester to help plugin authors catch bugs.
Besides flat config in general, the two notable changes to the rule tester that require changes to this test suite are:
- it's now an error to have …
> test: run against ESLint v9

- lib/create-testing-library-rule/detect-testing-library-utils.ts
- lib/create-testing-library-rule/index.ts
- lib/rules/no-await-sync-events.ts
- lib/rules/prefer-query-by-disappearance.ts
- lib/utils/types.ts
- package-lock.json
- package.json
Second part of migration to latest `typescript-eslint` version
CC/ @G-Rath @JoshuaKGoldberg
> feat(deps): update to `@typescript-eslint/*` v7

- package-lock.json
- package.json
Needed for #955, otherwise NPM will complain about incompatible `@typescript-eslint/parser` versions
CC/ @G-Rath
---
Closes #951
> feat(deps-dev): update `eslint-plugin-jest`

- index.d.ts
- package.json
- adds types so that usage with `eslint.config.js` in TypeScript codebases don't result in errors
Now that plugins are imported "naturally" they can be type-checked by TypeScript so it's useful to ship types - for now I've just manually typed the plugin since primarily the only useful thing to have typed is the configs, as things like rules and settings are still not implicitly inferred and trying to automate this would be overkill.
These types match those that we've got in `eslint-plugin-jest`, `eslint-plugin-jest-dom`, and other places
> feat: add TypeScript types

- index.d.ts
- switches the types back to using the `Linter.FlatConfig` type to ensure compatibility with both ESLint v8 and v9
#973 incorrectly changed this probably because `Linter.FlatConfig` is marked as deprecated in v9, but it's the correct type to be using when supporting both v8 and v9 because `@types/eslint` (for v8) `Linter.Config`  maps to _legacy_ config - so right now the actual types for `flat/*` will change depending on the version of ESLint you've got installed.
> fix: use valid config type for supporting both ESLint v8 and v9

- .npmrc
- Add `commitlint` packages to the pnpm public hoist pattern
commitlint is currently broken for the `commit-msg` hook because pnpm can't find the right dependencies. This is caused by the private hoist mechanism from pnpm. For fixing it, I just made all the commitlint packages publicly hoisted. [More info in this issue](https://github.com/conventional-changelog/commitlint/issues/645).
> chore: fix commitlint local setup

- docs/rules/prefer-screen-queries.md
- Add missing import of "within" in example code of `prefer-screen-queries`.
> docs: fix example in prefer-screen-queries.md

- lib/node-utils/index.ts
- tests/lib/rules/await-async-queries.test.ts
> fix(await-async-queries): false positive with optional chaining

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/propose_new_rule.yml
- .github/ISSUE_TEMPLATE/request_general_change.yml
- .github/ISSUE_TEMPLATE/request_rule_change.yml
Update issue templates for:
- Adding `type` set to "feature", "task", or "bug".
- Removing unnecessary fields 
N/A
> chore: update issue templates

- docs/rules/prefer-find-by.md
- lib/rules/prefer-find-by.ts
- tests/lib/rules/prefer-find-by.test.ts
Hi 👋 This is my first contribution — thank you for the great work on this project!
- Introduced auto-fix support to the `prefer-find-by` rule.
- Fixes cases where `findBy*` queries are unnecessarily wrapped inside `waitFor`.
Fixes #910
> feat(prefer-find-by): add fixer for waitFor wrapping findBy queries

- package.json
- tests/index.test.ts
- tests/lib/rules/no-wait-for-side-effects.test.ts
- tests/lib/rules/prefer-find-by.test.ts
- tsconfig.build.json
- tsconfig.json
I noticed several type errors in the `tests` directory, so I updated the config to include them in type-checking.
Let me know what you think!
- Created a separate `tsconfig.build.json` for build purposes.
→ To `type-check` both `lib` and `tests`, but exclude `tests` from the build output.
- Fixed type errors that appeared during `type-check`.
> refactor: Include test files in type checking

- docs/rules/no-node-access.md
- lib/rules/no-node-access.ts
- lib/utils/index.ts
- tests/lib/rules/no-node-access.test.ts
- Extended the `no-node-access` rule to also disallow direct calls to DOM event methods like `.click()`, `.focus()`, `.blur()`, `.select()`, and `.submit()`.
#752
> feat(no-node-access): extend no-node-access to disallow DOM event methods

- lib/rules/no-node-access.ts
- tests/lib/rules/no-node-access.test.ts
I have applied the temporary workaround that was proposed in #1024.
Sorry for the inconvenience, but I would appreciate your review.🙇‍♂️
- Temporarily exclude the variable name 'user' from the no-node-access rule to avoid false positive errors when using `const user = userEvent.setup()`.
#1024 （partially）
> fix(no-node-access): exclude `user` to avoid false positives

- docs/rules/no-node-access.md
- lib/utils/index.ts
- remove 'focus' from `EVENT_HANDLER_METHODS` for consistency
Fixes #1027
> fix(no-node-access): stop reporting `focus()` usage

- docs/rules/no-node-access.md
- lib/utils/index.ts
- remove `blur` from EVENT_HANDLER_METHODS for consistency.
- update document.
Fixes #1030
> fix(no-node-access): stop reporting blur() usage

- docs/rules/await-async-queries.md
- docs/rules/await-async-utils.md
- lib/node-utils/index.ts
- tests/lib/rules/await-async-events.test.ts
- tests/lib/rules/await-async-queries.test.ts
- tests/lib/rules/await-async-utils.test.ts
This expands support for additional async matchers (specifically, [jasmine](https://jasmine.github.io/api/edge/async-matchers.html)) to reduce false positives for `await-async-queries` and `await-async-utils`. As mentioned in the linked issue, I understand any hesitancy to include framework-specific logic, but I think this is a relatively trivial addition to open up support to another testing framework.
Fixes https://github.com/testing-library/eslint-plugin-testing-library/issues/1039
> feat: expand async matcher support

- lib/rules/await-async-utils.ts
- tests/lib/rules/await-async-events.test.ts
- tests/lib/rules/await-async-queries.test.ts
- tests/lib/rules/await-async-utils.test.ts
This tweaks the logic in `isAssigningKnownAsyncFunctionWrapper` to account for return values being assigned to variables. This only impacted `await-async-utils`, as it is less common to assign the result of an async util to a variable than it is an async query. I've added additional test cases to `await-async-queries` and `await-async-events` to explicitly protect against regressions in this behavior.
Fixes #1046
> fix: handled promises assigned to vars are valid

- lib/rules/no-node-access.ts
- lib/rules/no-render-in-lifecycle.ts
- lib/rules/no-unnecessary-act.ts
- lib/rules/prefer-query-matchers.ts
- lib/rules/prefer-user-event.ts
Some rules, for example [no-node-access](https://github.com/testing-library/eslint-plugin-testing-library/blob/35e2b406241c816bf52439075dfc61f0964ca494/lib/rules/no-node-access.ts#L37) currently allow extra properties to be passed in options object, which should not be allowed. This makes it easier for typos in rule options to go unnoticed.
This PR simply disallows extra properties in rules' schemas which currently allow them.
> fix: disallow extra properties in rule options

- lib/rules/no-node-access.ts
- tests/lib/rules/no-node-access.test.ts
- Improved detection of user-event calls from render-returned objects in custom testing utilities.
Fixes: Comments below
https://github.com/testing-library/eslint-plugin-testing-library/pull/1033#pullrequestreview-3000041608
> fix(no-node-access): support user-event instances returned from custom render

- lib/rules/await-async-utils.ts
- tests/lib/rules/await-async-queries.test.ts
- tests/lib/rules/await-async-utils.test.ts
This prevents false positives for the case where async utils are referenced but not called. This matches the behavior in both `await-async-events` and `await-async-queries`. `await-async-events` explicitly tests for this behavior [here](https://github.com/puglyfe/eslint-plugin-testing-library/blob/allow-async-refs/tests/lib/rules/await-async-events.test.ts#L43-L51) and [here](https://github.com/puglyfe/eslint-plugin-testing-library/blob/allow-async-refs/tests/lib/rules/await-async-events.test.ts#L282-L290). `await-async-queries` doesn't explicitly test for this, but follows a similar implementation of only processing `CallExpression` nodes rather than `CallExpression Identifier` nodes.
- Allow un-called references in `await-async-utils`
- Add tests to `await-async-queries` to prevent …
> fix: allow un-called async util references

- lib/rules/no-node-access.ts
- tests/lib/rules/no-node-access.test.ts
- Add support for detecting userEvent instances assigned via AssignmentExpression.
- Move `userEventInstanceNames` into the `create` function scope to avoid cross-file caching issues.
- https://github.com/testing-library/eslint-plugin-testing-library/issues/1038#issuecomment-3062146982
- https://github.com/testing-library/eslint-plugin-testing-library/issues/1057
> fix: support AssignmentExpression in userEvent setup detection

- docs/rules/await-async-queries.md
- docs/rules/await-async-utils.md
- lib/node-utils/index.ts
- tests/lib/rules/await-async-events.test.ts
- tests/lib/rules/await-async-queries.test.ts
- tests/lib/rules/await-async-utils.test.ts
- replaces `hasChainedThen` with `hasChainedPromiseHandler` in the `isPromiseHandled` logic
- adds tests to all async rules that utilize this code path
I'm a bit curious if there's a reason why this pattern wasn't supported previously. I know it's possible to rewrite tests to use async matchers, but this seems like something that the plugin should allow. Let me know if there's something I'm not considering here...
edit: github cached the PR title from my previous contribution 🤔 not sure what happened there.
closes https://github.com/testing-library/eslint-plugin-testing-library/issues/1058
> fix: `catch` handles promise

- docs/rules/no-wait-for-multiple-assertions.md
- lib/rules/no-wait-for-multiple-assertions.ts
- tests/lib/rules/no-wait-for-multiple-assertions.test.ts
- Updated rule logic to better distinguish between unique async elements.
- Update doc and test.
Fixes #1084 
---
This is completely unrelated to the changes in this PR, but I noticed an [error](https://github.com/testing-library/eslint-plugin-testing-library/actions/runs/18224863863/job/51893411818?pr=1097#step:8:273) in the "Upload coverage reports to Codecov" step, and the coverage notification is not being sent.  
Is this something we should be concerned about, or is it fine to ignore?
> feat(no-wait-for-multiple-assertions): avoid reporting unrelated assertions
