testing-library/eslint-plugin-testing-library

.huskyrc
commitlint.config.js
package-lock.json
package.json

This PR intends to add [commitlint](https://commitlint.js.org/#/) to the codebase to enforce good commit messages.
The convention followed can be found [here](https://www.conventionalcommits.org/en/v1.0.0-beta.4/).

feat: add commitlint and commit-msg hook

---

README.md

Adds autofixable column for indicating which supported rules can be autofixed.
Result can be checked here: https://github.com/Belco90/eslint-plugin-testing-library/tree/feature/add-autofix-doc

docs: add autofixable column for supported rules

---

lib/rules/await-async-query.js
lib/rules/await-fire-event.js
tests/lib/rules/prefer-expect-query-by.js

We had some tiny cases uncovered in our code. This PR intends to reach 100% code coverage to make sure our code is fully covered by our test suite 🎉 
I'm usually not in favor of 100% code coverage in web applications but I think that's worth it for an open source software users will rely on.
Should we add a coverage check in our `jest` config by the way?

test: reach 100% code coverage

---

README.md

For some reason, displaying GitHub badges under All Contributors broke it.

docs: github badges

---

lib/rules/no-manual-cleanup.ts
tests/lib/rules/no-manual-cleanup.test.ts

fix(no-manual-cleanup): check require imports properly

---

README.md

docs: fix reference to configurations column

---

docs/rules/prefer-screen-queries.md
tests/lib/rules/prefer-screen-queries.test.ts

Adds a few tests and updates the docs to reflect the scenarios discussed in #178

test: include tests from methods not available in screen

---

lib/detect-testing-library-utils.ts
lib/node-utils.ts
lib/rules/await-async-utils.ts
lib/rules/no-await-sync-query.ts
lib/rules/no-wait-for-multiple-assertions.ts
lib/rules/no-wait-for-side-effects.ts
lib/rules/prefer-find-by.ts
tests/lib/rules/await-async-utils.test.ts
tests/lib/rules/no-await-sync-query.test.ts
tests/lib/rules/no-wait-for-multiple-assertions.test.ts
tests/lib/rules/no-wait-for-side-effects.test.ts
tests/lib/rules/prefer-find-by.test.ts

fix: first round of bugfixes for v4

---

.github/dependabot.yml
package.json

I also added Dependabot, so you'll get automatic dependency update PRs

chore: update dependencies

---

lib/rules/prefer-screen-queries.ts
package.json

fix: third round of bug fixes

---

CONTRIBUTING.md

docs: update contributing guidelines to v4

---

.github/workflows/pipeline.yml
.lintstagedrc
package.json

My IDE keeps complaining about this file (probably because I have enabled a Prettier plugin)

chore: prettify codebase

---

.github/workflows/pipeline.yml

https://nodejs.medium.com/node-js-16-available-now-7f5099a97e70

chore: add tests for Node 16

---

CONTRIBUTING.md

Closes https://github.com/testing-library/eslint-plugin-testing-library/issues/356
Haven't added any info on how to try changes locally, as I don't think it's very important anymore.

docs: improve CONTRIBUTING

---

lib/rules/prefer-user-event.ts
tests/lib/rules/prefer-user-event.test.ts

fix(prefer-user-event): prevent crash with custom `createEvent` function

---

lib/node-utils/is-node-of-type.ts
lib/rules/no-unnecessary-act.ts
tests/lib/rules/no-unnecessary-act.test.ts

Closes https://github.com/testing-library/eslint-plugin-testing-library/issues/417

fix(no-unnecessary-act): fix false positives when `isStrict` option is set to `false`

---

.github/ISSUE_TEMPLATE/request_general_change.yml

- Create request general change form
Go to https://github.com/HonkingGoose/eslint-plugin-testing-library/blob/chore/430-request-general-change-form/.github/ISSUE_TEMPLATE/request_general_change.yml to see the preview.
Helps with #430.
You can click another checkbox after this PR is merged.

chore: create request general change form

---

.husky/commit-msg
.husky/pre-commit
.huskyrc
package.json

- upgrade husky from v4 to v7
- upgrade lint-staged from v10 to v11

build(deps-dev): upgrade husky and lint-staged

---

.github/workflows/smoke-test.yml
package.json
tests/eslint-remote-tester.config.js

- Adds smoke tests to the project
- Adds two new development dependencies
- Adds one new Github Action
Github Action will be run once a week by a schedule. It can also be triggered manually. In addition it is also run after each release as requested in https://github.com/testing-library/eslint-plugin-testing-library/issues/341#issuecomment-819799954. 
When `eslint-remote-tester` finds errors it will create an issue in this project. Here are some example reports: https://github.com/yannickcr/eslint-plugin-react/issues?q=author%3Aapp%2Fgithub-actions. 
Closes #341.
- Use case description: https://github.com/AriPerkkio/eslint-remote-tester#plugin-maintainer-making-sure-all-existing-rules-do-not-crash
- Used Github Action: https://github.com/AriPerkkio/eslint-remote-tester-run-action
- …

test: add smoke tests

---

.github/workflows/pipeline.yml
lib/create-testing-library-rule/index.ts
package.json

fix: update dependencies

---

docs/rules/consistent-data-testid.md

Updating docs to fix https://github.com/testing-library/eslint-plugin-testing-library/issues/451 (for now). Ideally I'll have some time to extend this rule to work with other libraries and not just react, but this adds some docs to make it more clear for now!

fix(docs): update docs for consistent-data-testid

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/pull_request_template.md

- PR template: add corresponding scripts to Checks section
- Bug template: add field to confirm troubleshooting was read
- Bug template: fix typos and improve some wording

ci: update GitHub templates

---

CODE_OF_CONDUCT.md

docs: update code of conduct to Contributor Covenant v2.1

---

tests/lib/rules/await-async-query.test.ts
tests/lib/rules/no-await-sync-query.test.ts
tests/lib/rules/no-promise-in-fire-event.test.ts
tests/lib/rules/no-wait-for-empty-callback.test.ts
tests/lib/rules/no-wait-for-multiple-assertions.test.ts
tests/lib/rules/no-wait-for-side-effects.test.ts
tests/lib/rules/prefer-find-by.test.ts
tests/lib/rules/prefer-query-by-disappearance.test.ts
tests/lib/rules/prefer-screen-queries.test.ts

Follow-up of #582
Added explicit tests for `@testing-library/dom`

test: refactor `@testing-library/dom` tests

---

README.md

- Fix ESLint logo URL in the README
Since ESLint released a new website, our previous reference to their logo was missed. Now it's pointing to their repo, which should be a more reliable resource.

docs: fix ESLint logo

---

.gitpod.yml

- Add a `.gitpod.yml` file with the initial config
No ticket related to this. Since I work in this repo from Gitpod quite often, I thought it would be a good idea to add the config

chore: add init gitpod config

---

README.md

Reverts testing-library/eslint-plugin-testing-library#851

docs: revert "update eslint pattern matching"

---

.github/workflows/release.yml

This will also add a new Provenance section + a verified badge next to the version (in the sidebar + versions tab) to the NPM page
More info can be found at https://docs.npmjs.com/generating-provenance-statements

fix: generate provenance statements on release

---

README.md

docs(README): add Svelte badge

---

docs/rules/no-wait-for-multiple-assertions.md

docs(rules/no-wait-for-multiple-assertions): fix typo
